# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['change_type'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmwid', models.CharField(max_length=25)),
                ('qc_comments', models.CharField(max_length=200, null=True)),
                ('qc_approved', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_field', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Water_QC.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('change_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Water_QC.ChangeType')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['feature_name'],
            },
        ),
        migrations.CreateModel(
            name='Geodatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geodatabase_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Water_QC.City')),
            ],
        ),
        migrations.CreateModel(
            name='MonthFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('folder_path', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='geodatabase',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Water_QC.MonthFolder'),
        ),
        migrations.AddField(
            model_name='featureclass',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Water_QC.FeatureType'),
        ),
        migrations.AddField(
            model_name='featureclass',
            name='geodatabase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Water_QC.Geodatabase'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Water_QC.FeatureClass'),
        ),
    ]
